### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by TitusKirch** [openauth-dev/SocialiteOpenAuthProvider#16]
If @SoftCreatR provide a contact mail, I can add code of conduct.

See: https://github.com/openauth-dev/SocialiteOpenAuthProvider/community/code-of-conduct/new?template=contributor-covenant

**Comment by SoftCreatR** [comment]
Want me to create an alias mail that forwards every incoming mail to the whole team?

**Comment by TitusKirch** [comment]
That would even be the optimal case. If necessary, you can create an alias for each project (to reach only the appropriate people). The structure of an alias mail could be like this `project.report@openauth.dev` (e.g. `socialiteopenauthprovider.report@openauth.dev`)

**Comment by SoftCreatR** [comment]
-> socialiteopenauthprovider.report@openauth.dev
